config/routes.rb
IBeaconCMS::Application.routes.draw do

  resources :template_wines
  match 'template_wines/new', to: 'template_wines#new', via: :post
  match 'template_wines/:id/edit', to: 'template_wines#edit', via: :post


  resources :template_photos

  resources :templates

  resources :beacon_devices
  match 'beacon_devices/add_device_to_beacon_range', to: 'beacon_devices#add_device_to_beacon_range', via: :post
  match 'beacon_devices/remove_device_from_beacon_range', to: 'beacon_devices#remove_device_from_beacon_range', via: :post

  resources :notifications
  match 'notifications/broadcast_notification', to: 'notifications#broadcast_notification', via: :post

  resources :apps

  devise_for :users
  resources :detections do
    post 'track'
  end

  resources :users
  match 'users/mobile_user', to: 'users#mobile_user', via: :post

  resources :items do
    member do
      get 'embedded'
      get 'kiosk'
      get 'template'
    end
  end

  resources :items
  match 'items/new', to:'items#new', via: :post
  match 'items/:id/edit', to:'items#edit', via: :post

  resources :beacons
  match 'beacons/content', to: 'beacons#content', via: :post
  match 'beacons/new', to: 'beacons#new', via: :post
  match 'beacons/:id/edit', to: 'beacons#edit', via: :post

  get 'home/index'
  root :to => 'home#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :beacon
end

app/controllers/notifications_controller.rb
require "urbanairship"

class NotificationsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)
    #get item content associated with the beacon
    begin
      beacon_item = Beacon.find(params[:beacon_id]).item
      if (params[:is_goodbye_content])
        html_content = beacon_item.goodbye_content.html_safe
      else
        html_content = beacon_item.content.html_safe
      end
      @notification.content = html_content
    rescue
      puts "No html content associated to the beacon: #{params[:beacon_id]}"
    end
    response = Urbanairship.push_rich_notification(params[:device_id], params[:os], html_content)

    respond_to do |format|
      if @notification.save && response && response["ok"]
        #format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @notification }
        format.json { render json: response, status: :created, location: @notification }
      else
        #format.html { render action: 'new' }
        #format.json { render json: @notification.errors, status: :unprocessable_entity }
        format.json { render json: response, status: :unprocessable_entity }
      end
    end
  end

  # beacon_id, html_content
  def broadcast_notification
    users = BeaconDevice.where(:beacon_id => params[:beacon_id])
    error = false
    message = ""
    error_num = 0
    users.each do |user|
      user = User.find(user.user_id)
      params[:notification][:device_id] = user.device_id
      params[:notification][:os] = user.os
      response = Urbanairship.push_rich_notification(user.device_id, user.os, params[:content])
      puts response
      if (response && response["ok"])
        notification = Notification.new(notification_params)
        notification.save!
      else
        error = true
        error_num = error_num + 1
        message += "error #" + error_num.to_s + ":" + response["details"]["error"] + ", "
      end
    end
    message = "notifications sent to all the devices near beacon: #{params[:beacon_id]}" unless (error == true)
    respond_to do |format|
      format.json { render json: {:ok => !error, :message => message}}
    end

  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @notification }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:device_id, :os, :beacon_id, :content)
    end
end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :device_id %>
    <%= f.input :os %>
    <%= f.association :beacon %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Os</th>
      <th>Beacon</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.device_id %></td>
        <td><%= notification.os %></td>
        <td><%= notification.beacon %></td>
        <td><%= notification.content %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @notification.device_id %>
</p>

<p>
  <strong>Os:</strong>
  <%= @notification.os %>
</p>

<p>
  <strong>Beacon:</strong>
  <%= @notification.beacon %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>