config/routes.rb
IBeaconCMS::Application.routes.draw do

  resources :template_wines
  match 'template_wines/new', to: 'template_wines#new', via: :post
  match 'template_wines/:id/edit', to: 'template_wines#edit', via: :post


  resources :template_photos

  resources :templates

  resources :beacon_devices
  match 'beacon_devices/add_device_to_beacon_range', to: 'beacon_devices#add_device_to_beacon_range', via: :post
  match 'beacon_devices/remove_device_from_beacon_range', to: 'beacon_devices#remove_device_from_beacon_range', via: :post

  resources :notifications
  match 'notifications/broadcast_notification', to: 'notifications#broadcast_notification', via: :post

  resources :apps

  devise_for :users
  resources :detections do
    post 'track'
  end

  resources :users
  match 'users/mobile_user', to: 'users#mobile_user', via: :post

  resources :items do
    member do
      get 'embedded'
      get 'kiosk'
      get 'template'
    end
  end

  resources :items
  match 'items/new', to:'items#new', via: :post
  match 'items/:id/edit', to:'items#edit', via: :post

  resources :beacons
  match 'beacons/content', to: 'beacons#content', via: :post
  match 'beacons/new', to: 'beacons#new', via: :post
  match 'beacons/:id/edit', to: 'beacons#edit', via: :post

  get 'home/index'
  root :to => 'home#index'

end

app/models/template_wine.rb
class TemplateWine < ActiveRecord::Base
  belongs_to :item
  mount_uploader :url_image_1, AvatarUploader
  scope :vineyard, -> {where(room_type:'filter1')}
  # scope :reserve, -> {where(room_type:'filterall')}
end

app/controllers/template_wines_controller.rb
class TemplateWinesController < ApplicationController
  before_action :set_template_wine, only: [:show, :edit, :update, :destroy]

  # GET /template_wines
  # GET /template_wines.json
  def index
    @template_wines = TemplateWine.all
  end

  # GET /template_wines/1
  # GET /template_wines/1.json
  def show
  end

  # GET /template_wines/new
  def new
    @template_wine = TemplateWine.new
    # @uploader = TemplateWine.new.url_image_1
    # @uploader.success_action_redirect = new_template_wine_url

  end

  # GET /template_wines/1/edit
  def edit
  end

  # POST /template_wines
  # POST /template_wines.json
  def create
    @template_wine = TemplateWine.new(template_wine_params)

    respond_to do |format|
      if @template_wine.save
        format.html { redirect_to @template_wine, notice: 'Template wine was successfully created.' }
        format.json { render :show, status: :created, location: @template_wine }
      else
        format.html { render :new }
        format.json { render json: @template_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /template_wines/1
  # PATCH/PUT /template_wines/1.json
  def update
    respond_to do |format|
      if @template_wine.update(template_wine_params)
        format.html { redirect_to @template_wine, notice: 'Template wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @template_wine }
      else
        format.html { render :edit }
        format.json { render json: @template_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_wines/1
  # DELETE /template_wines/1.json
  def destroy
    @template_wine.destroy
    respond_to do |format|
      format.html { redirect_to template_wines_url, notice: 'Template wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template_wine
      @template_wine = TemplateWine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_wine_params
      params[:template_wine].permit(:name, :taste_notes, :price ,:wine_specs_vintage,:wine_specs_sugar,:wine_specs_appellation, :wine_specs_acid , :wine_specs_alcohol, :wine_specs_ph, :photo_link, :wine_specs_price_description,:url_image_1,:remove_url_image_1, :item_id,:room_type,:sort_column)
    end
end

app/views/template_wines/_form.html.haml
= simple_form_for(@template_wine,:wrapper => :bootstrap_horizontal,  html: {class: 'form-horizontal', :multipart => true }) do |f|
  %section.row
    %section.col-lg-12
      = f.input :name
      = f.input :taste_notes
      = f.input :price
      = f.input :photo_link
      = f.input :wine_specs_sugar
      = f.input :wine_specs_vintage
      = f.input :wine_specs_appellation
      = f.input :sort_column
      -#= f.input :wine_specs_alcohol
      -#= f.input :wine_specs_ph
      = f.input :wine_specs_price_description
      -#room type
      = f.select :room_type,  [["Choose a room type",""],["vineyard","filter1"],["all","retail"]]
  %section.row
    %p
      = f.file_field :url_image_1
    %p
      %label
        Remove url_image_1
        = f.check_box :remove_url_image_1


      -#= f.association :item
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit

app/views/template_wines/edit.html.erb
<h1>Editing template_wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @template_wine %> |
<%= link_to 'Back', template_wines_path %>

app/views/template_wines/index.html.haml
%h1 Listing templates Wines
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Name
      %th Taste Notes
      %th Price
      %th Photo link
      %th Wine Specs Vintage
      %th Wine Specs Sugar
      %th Wine Specs Appellation
      -#%th Wine Specs Acid
      -#%th Wine Specs Alcohol
      %th Wine Sort Order
      %th Wine Specs Price Description
      %th Item Remote Photo link
      %th Item Id
      %th Edit
  %tbody
    - @template_wines.each do |template_wine|
      %tr
        %td= template_wine.id
        %td= template_wine.name
        %td= template_wine.taste_notes
        %td= template_wine.price
        %td= template_wine.photo_link
        %td= template_wine.wine_specs_vintage
        %td= template_wine.wine_specs_sugar
        %td= template_wine.wine_specs_appellation
        -#%td= template_wine.wine_specs_acid
        -#%td= template_wine.wine_specs_alcohol
        %td= template_wine.sort_column
        %td= template_wine.wine_specs_price_description
        -if !template_wine.url_image_1.nil?
          %td= image_tag(template_wine.url_image_1)
        %td= template_wine.item_id
        %td= button_to('Edit Wine', edit_template_wine_path(template_wine), :class => 'btn btn-large btn-primary')
        %td= button_to( "Delete", template_wine_path(template_wine), method: :delete, data: { confirm: 'Are you certain you want to delete this?' },:class => 'btn btn-large btn-primary');
= button_to('New Wine', new_template_wine_path, :class => 'btn btn-large btn-primary')

app/views/template_wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', template_wines_path %>

app/views/template_wines/show.html.haml
%p#notice= notice
%p
  %strong Id:
  = @template_wine.id
%p
  %strong Name:
  = @template_wine.name
%p
  %strong  Price:
  = @template_wine.photo_link
%p
  %strong Taste Notes:
  = @template_wine.taste_notes
%p
  %strong  Photo link:
  = @template_wine.photo_link
%p
  %strong Wine Vintage:
  = @template_wine.wine_specs_vintage
%p
  %strong Wine Sugar:
  = @template_wine.wine_specs_sugar
-#%p
-#  %strong Wine PH:
-#  = @template_wine.wine_specs_ph
-#%p
-#  %strong Wine alcohol:
-#  = @template_wine.wine_specs_alcohol
%p
  %strong Sort Order:
  = @template_wine.sort_column
%p
  %strong Wine Price Description:
  = @template_wine.wine_specs_price_description
%p
  %strong Item Id:
  = @template_wine.item_id
%p
  %strong image1:
  = image_tag(@template_wine.url_image_1)

= link_to 'Edit', edit_template_wine_path(@template_wine)
|
= link_to 'Back', template_wines_path