config/routes.rb
IBeaconCMS::Application.routes.draw do

  resources :template_wines
  match 'template_wines/new', to: 'template_wines#new', via: :post
  match 'template_wines/:id/edit', to: 'template_wines#edit', via: :post


  resources :template_photos

  resources :templates

  resources :beacon_devices
  match 'beacon_devices/add_device_to_beacon_range', to: 'beacon_devices#add_device_to_beacon_range', via: :post
  match 'beacon_devices/remove_device_from_beacon_range', to: 'beacon_devices#remove_device_from_beacon_range', via: :post

  resources :notifications
  match 'notifications/broadcast_notification', to: 'notifications#broadcast_notification', via: :post

  resources :apps

  devise_for :users
  resources :detections do
    post 'track'
  end

  resources :users
  match 'users/mobile_user', to: 'users#mobile_user', via: :post

  resources :items do
    member do
      get 'embedded'
      get 'kiosk'
      get 'template'
    end
  end

  resources :items
  match 'items/new', to:'items#new', via: :post
  match 'items/:id/edit', to:'items#edit', via: :post

  resources :beacons
  match 'beacons/content', to: 'beacons#content', via: :post
  match 'beacons/new', to: 'beacons#new', via: :post
  match 'beacons/:id/edit', to: 'beacons#edit', via: :post

  get 'home/index'
  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :beacon
  has_one :template
  accepts_nested_attributes_for :template
  has_one :template_photo
  accepts_nested_attributes_for :template_photo
  has_one :template_wine
  validates :spec,:presence => true, allow_blank: false
  validates :name,:presence => {:message => 'Please pick Template Article /Template Photo'}, allow_blank: false


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #before_filter :authenticate_user!

  before_action :set_item, only: [:show, :edit, :update, :destroy, :embedded, :kiosk]

  # GET /items
  def index
    @items = Item.all
    @templates = Template.all
    @template_photos = TemplatePhoto.all
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
    if (@item.name == 'Template1')
      @item.template_photo = TemplatePhoto.new
    elsif (@item.name == 'Template2')
      @item.template = Template.new
    else
      @item.template_photo = TemplatePhoto.new
      @item.template = Template.new
    end

  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /items/1
  def destroy
    @template = Template.find(@item.template)
    @template_photo = TemplatePhoto.find(@item.template_photo)
    @template.destroy
    @template_photo.destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end


  # Get /items/1/embedded
  # Used by mobile app to display item content
  def embedded
    render layout: 'compact'
  end

  # Get /items/1/kiosk
  # Used by mobile app to display item video
  def kiosk
    render layout: 'compact'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:spec,
                                   :name,
                                   :description,
                                   :beacon_id,
                                   :content,
                                   :template_id,
                                   :show_after_seconds,
                                   template_attributes:[:id,:name,:description_1,:photo_link_1,:url_image_1,:item_id],
                                   template_photo_attributes:[:id,:name,:title,:description,:photolink,:url_image_1,:item_id])
    end


    def resolve_layout
      case action_name
        when 'embedded'
          'compact'
        else
          'application'
      end
    end
end

app/views/items/_form.html.haml
= simple_form_for(@item,:wrapper => :bootstrap_horizontal,  html: {class: 'form-horizontal', :multipart => true }) do |f|
  %section.row
    %section.col-lg-2
      = f.label :spec, 'Beacon location'
    %section.col-lg-6
      = @item.spec
  %section.row
    %section.col-lg-2
      = f.label :name, 'Template'
    %section.col-lg-6
      = f.select :name,  [["Choose a template",""],["Photo Template","Template1"],["Article Template", "Template2"],["Wine List", "Template3"]]
  %section.row
    %section.col-lg-2
      = f.label :description, 'Description'
    %section.col-lg-6
      = f.input_field :description
  %section.row
    %section.col-lg-2
      = f.label :show_after_seconds, 'Show after seconds'
    %section.col-lg-6
      = f.input_field :show_after_seconds
  %section.row
    %section.col-lg-2
      = f.label :beacon, 'Beacon'
    %section.col-lg-8
      = f.association :beacon, label_method: :description,label:false
    %section.row
    - if @item.name == 'Template1'
      .TemplateArticle.hide
        %h4.something Template Article Asssociation
        = f.simple_fields_for :template, @item.template do |template_builder|
          = render 'template2_partial', :template_builder => template_builder
      .TemplatePhoto
        %h4.something Template Photo Asssociation
        = f.simple_fields_for :template_photo, @item.template_photo do |template_photo_builder|
          = render 'template1_partial', :template_photo_builder => template_photo_builder
    - elsif @item.name == 'Template2'
      .TemplateArticle
        %h4.something Template Article Asssociation
        = f.simple_fields_for :template, @item.template do |template_builder|
          = render 'template2_partial', :template_builder => template_builder
      .TemplatePhoto.hide
        %h4.something Template Photo Asssociation
        = f.simple_fields_for :template_photo, @item.template_photo do |template_photo_builder|
          = render 'template1_partial', :template_photo_builder => template_photo_builder
    - else
      .TemplateArticle.hide
        %h4.something Template Article Asssociation
        = f.simple_fields_for :template, @item.template do |template_builder|
          = render 'template2_partial', :template_builder => template_builder
      .TemplatePhoto.hide
        %h4.something Template Photo Asssociation
        = f.simple_fields_for :template_photo, @item.template_photo do |template_photo_builder|
          = render 'template1_partial', :template_photo_builder => template_photo_builder
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit

app/views/items/_template1_partial.html.haml
%section.row
%section.col-lg-4
  = template_photo_builder.label :name, "Template Photo Name"
%section.col-lg-8
  = template_photo_builder.input_field :name
%section.col-lg-4
  = template_photo_builder.label :title, "Template Title"
%section.col-lg-8
  = template_photo_builder.input_field :title
%section.col-lg-4
  = template_photo_builder.label :description, "Template Description"
%section.col-lg-8
  = template_photo_builder.input_field :description
%section.col-lg-4
  = template_photo_builder.label :photolink, "Photo link Local(Phone)"
%section.col-lg-8
  = template_photo_builder.input_field :photolink
%section.col-lg-4
  = template_photo_builder.label :url_image_1, "Url Image"
%section.col-lg-8
  = template_photo_builder.file_field :url_image_1
%section.col-lg-4
  = template_photo_builder.label :item, "Related Page Same as beacon location, if new location leave blank fill in later with edit operation "
%section.col-lg-8
  = template_photo_builder.association :item,label_method: :description, label:false

app/views/items/_template2_partial.html.haml
%section.row
  %section.col-lg-4
    = template_builder.label :name, "Template Article Name"
  %section.col-lg-8
    = template_builder.input_field :name
  %section.col-lg-4
    = template_builder.label :description_1, "Template Description"
  %section.col-lg-8
    = template_builder.input_field :description_1
  %section.col-lg-4
    = template_builder.label :photo_link_1, "Photo link Local(Phone)"
  %section.col-lg-8
    = template_builder.input_field :photo_link_1
  %section.col-lg-4s
    = template_builder.label :url_image_1, "Url Image "
  %section.col-lg-8
    = template_builder.file_field :url_image_1
  %section.col-lg-4
    = template_builder.label :item, "Related Page Same as beacon location, if new location leave blank fill in later with edit operation "
  %section.col-lg-8
    = template_builder.association :item,label_method: :description, label:false

app/views/items/edit.html.haml
%h1 Editing item
= render 'form'
= link_to 'Show', @item
|
\#{link_to 'Back', items_path}

app/views/items/embedded.html.haml
-#TODO: Force bootstrap ?
%section.col-lg-12.col-md-12.col-sm-12.col-xs-12
  = @item.content.html_safe

app/views/items/index.html.haml
%h1 Listing items
%table.table.table-striped
  %thead
    %tr
      %th Spec
      %th Name
      %th Description
      %th Timeframe
      %th Beacon
      %th Template_id
      %th
      %th
      %th
  %tbody
    - @items.each do |item|
      %tr
        %td= item.beacon.location
        %td= item.name
        - if item.name == 'Template1'
          %td= item.template_photo.description
        - elsif item.name == 'Template2'
          %td= item.template.description_1
        - else
          %td= "No Description"
        %td= item.show_after_seconds
        %td= item.beacon.major.to_s + ' - ' + item.beacon.minor.to_s
        %td= item.beacon.app.id.to_s
        -#%td= items.template_id
        -#%td= link_to 'Show', item
        %td= button_to('Edit', edit_item_path(item), :class => 'btn btn-large btn-primary')
        %td= button_to('Destroy',item, :class => 'btn btn-medium btn-primary', method: :delete, data: { confirm: 'Are you sure?' })
%br/
= button_to('New Page', new_item_path, :class => 'btn btn-large btn-primary')

app/views/items/kiosk.html.haml
:javascript
  var beaconId = "#{@item.beacon_id}"
-#TODO: Force bootstrap ?
%section.col-lg-12.col-md-12.col-sm-12.col-xs-12
  = @item.video.html_safe unless @item.nil? || @item.video.nil?

app/views/items/new.html.haml
%h1 New Page
.flash-notice.alert.alert-danger
  = @item.errors.full_messages.to_s

= render 'form'
= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice
%p
  %strong Spec:
  = @item.spec
%p
  %strong Name:
  = @item.name
%p
  %strong Description:
  = @item.description
%p
  %strong Beacon:
  = @item.beacon

-if (@item.name == 'Template1')
  %p
    %strong Description:
    = @item.template_photo.description
  %p
    %strong Photo Link:
    = @item.template_photo.photolink
-else
  %p
    %strong Description:
    = @item.template.description_1
  %p
    %strong Photo Link:
    = @item.template.photo_link_1

= link_to 'Edit', edit_item_path(@item)

|
\#{link_to 'Back', items_path}
|
\#{link_to 'Mobile Version', embedded_item_path(@item)}
|
\#{link_to 'Kiosk', kiosk_item_path(@item)}